all: Enfermero2.class Cliente2.class Medico2.class Paramedico2.class Servidor2.class Distribuidos2.class

Enfermero2.class: Enfermero2.java
	javac Enfermero2.java

Cliente2.class: Cliente2.java
	javac Cliente2.java

Medico2.class: Medico2.java
	javac Medico2.java

Paramedico2.class: Paramedico2.java
	javac Paramedico2.java

Servidor2.class: Servidor2.java
	javac Servidor2.java

Distribuidos2.class: Distribuidos2.java
		javac Distribuidos2.java

Distribuidos2:
	java Distribuidos2

clean :
	rm -f *.class
