all: Enfermero.class Cliente.class Medico.class Paramedico.class Servidor.class Distribuidos.class

Enfermero.class: Enfermero.java
	javac Enfermero.java

Cliente.class: Cliente.java
	javac Cliente.java

Medico.class: Medico.java
	javac Medico.java

Paramedico.class: Paramedico.java
	javac Paramedico.java

Servidor.class: Servidor.java
	javac Servidor.java

Distribuidos.class: Distribuidos.java
		javac Distribuidos.java

Distribuidos:
	java Distribuidos

clean :
	rm -f *.class
